version: 2
jobs:
  build:
    docker:
      - image: brinkos-ci
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run: |
            # docker build -t brinkos/brinkos .
            docker pull brinkos/brinkos
      - run: |
            # starting container with our application
            # make sure you're not using `--rm` option otherwise container will be killed after finish
            docker run --privileged --name brinkos-build brinkos/brinkos

      - run: |
            # once application container finishes we can copy artifacts directly from it
            # RELEASE_DATE=$(date +%Y.%m.%d)
            docker cp brinkos-build:/iso/brinkOS-$(date +%Y.%m.%d)-x86_64.iso ./
            ls -lart
