version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - setup_remote_docker:
            docker_layer_caching: true
      - checkout
      - run: |
            docker build -t brinkOS/brinkOS .
